server:
  port: 8080

spring:
  datasource:
    # 数据库连接地址：
    # 127.0.0.1:3378 表示连接本机 MySQL 8 的 3378 端口
    # ick7778 是项目数据库名
    url: jdbc:mysql://127.0.0.1:3378/ick7778?useSSL=false&allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai

    # MySQL 用户名
    username: root

    # MySQL 密码
    password: "0721"

  # Redis 配置：Docker Redis 默认映射到本机 6379
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      timeout: 3000ms

  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 20MB

app:
  jwt:
    secret: "bWluaS1zZWNvbmQtaGFuZC1wbGF0Zm9ybS1qd3Qtc2VjcmV0LTEyMzQ1Njc4OTAxMjM0NTY3ODkw"
    expires-minutes: 120